config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
  get "generate_password_for_current_user", to: "home#generate_password_for_current_user", as: :generate_password_for_current_user
  get "generate_data_for_every_session", to: "home#generate_data_for_every_session", as: :generate_data_for_every_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def generate_password_for_current_user
    respond_to do |format|
      format.turbo_stream
    end
  end

  def generate_data_for_every_session
    DataGeneratorService.generate_uuid_and_append_name
    head :no_content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/generate_password_for_current_user.turbo_stream.erb
<%= turbo_stream.update "password_for_me", plain: Faker::Internet.password %>

app/views/home/index.html.erb
<h1>Generator</h1>
<h2>Password for me</h2>
<%=link_to 'Generate password just for me', generate_password_for_current_user_path, data: { turbo_stream: true } %><br /><br />
<%=turbo_frame_tag :password_for_me do %>
Password just for me
<% end %>
<hr />
<%=link_to 'Generate data for every session', generate_data_for_every_session_path, data: {"turbo-prefetch": false, turbo: false} %><br /><br />
<%=turbo_stream_from :data_generator_service %>
<%=turbo_frame_tag :uuid do %>
New UUID here
<% end %>
<hr />
<%=turbo_frame_tag :name do %>
New NAME here
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Data Generator" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://unpkg.com/simpledotcss/simple.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>